### ISSUE TITLE
fonts/{type1,truetype}: x/image/font.Face interface

### ISSUE THREAD

**Issue by sbinet** [benoitkugler/textlayout#2]
hi,

(apologies if that's not the best place to ask this type of question. feel free to point me to the correct forum otherwise).

any reason why the `type1` and `truetype` types do not integrate well with the `x/image/font` interfaces? (such as `font.Face`).
it would be great to have this kind of inter-operability.

(also, any reason you'd reimplement `x/image/font/sfnt` in `truetype`?)

**Comment by benoitkugler** [comment]
Hi,

This package is primarily oriented to text layout, where you don't need to do the actual drawing of glyphs. 
It seems to me that the x/image/font package is more oriented towards drawing (see for example the dependency on the image package).

> also, any reason you'd reimplement x/image/font/sfnt in truetype?

This package is experimental, so I wanted to "do it my way" (although many functions are directly copied from x/image/font/sfnt). Also, some features were missing from x/image/font/sfnt (advanced layout tables for instance). Generally speaking, it felt easier to start from scratch (with insights from existing implementations), to have free hands and try and find the best interfaces possible. 

(By the way, it is still a work in progress, and many things need to be cleaned up.)

**Comment by sbinet** [comment]
thanks for the rationale.
