### ISSUE TITLE
Are parsed fonts safe for concurrent use?

### ISSUE THREAD

**Issue by whereswaldon** [benoitkugler/textlayout#20]
I'm guessing that the answer is "no", but I can't find documentation either way. I'm interested in whether multiple Gio application windows can shape text with the same underlying `*truetype.Font` concurrently.

**Comment by benoitkugler** [comment]
Good question. I'll need to think about it more carefully, but I think it actually should be OK, since the `*Font` object is in fact a read-only (smart) view of the underlying font file.
However, it has never been tested.

**Comment by benoitkugler** [comment]
Looking at it more carefully, I see that the `*Font` object is _mostly_ read-only, with the exception of variable coordinates. 
It is in fact kind of unfortunate that the `*Font` stores the user provided `varCoords`.

Closing for now, feel free to re-open if you need more information !
