### ISSUE TITLE
When `langStr` is `utf-8`, NewOTTagsFromScriptAndLanguage fails

### ISSUE THREAD

**Issue by rznewswav** [benoitkugler/textlayout#26]
I was loading a font, but I cannot share it here. However, upon debugging, I found out that `languageToString` will return `utf-8`, and the loop will fail because of the `s+1` expression.

https://github.com/benoitkugler/textlayout/blob/9459f671349eb2b463ea5dcfc8739e793b07a323/harfbuzz/ot_tag.go#L309-L317

**Comment by benoitkugler** [comment]
See also https://github.com/go-text/typesetting/issues/64
