### ISSUE TITLE
Data error TRAK.ttf in v.0.0.10.zip

### ISSUE THREAD

**Issue by jonegil** [benoitkugler/textlayout#8]
Installing textlayout gives 

``` 
go get -v github.com/benoitkugler/textlayout@v0.0.10
go: downloading github.com/benoitkugler/textlayout v0.0.10
go: github.com/benoitkugler/textlayout@v0.0.10: stream error: stream ID 1; NO_ERROR; received from peer`
```

I can't recreate on mac, but on 4 various windows machines on different networks, all with well functioning downloads of other packages.

When manually unzip'ing @v0.0.10.zip with 7zip on windows, a data error is reported. 
`Data error : github.com\benoitkugler\textlayout@v0.0.10\fonts\truetype\testdata\layout_fonts\morx\TRAK.ttf`

Could these be related?

**Comment by benoitkugler** [comment]
Hi ! I'm not sure how to help you resolving this issue. I've tried to manually unzip v0.0.10.zip (https://github.com/benoitkugler/textlayout/archive/refs/tags/v0.0.10.zip) on Windows7 with 7zip, and didn't encountered any error.

**Comment by whereswaldon** [comment]
Okay, so my hypothesis has no evidence so far.

I tried tricking go into redownloading the module so that I could get at the zip file from the module cache:

```shell
cd /tmp
mkdir foo
cd foo
go mod init whatever.com
mkdir go
GOPATH=/tmp/foo/go go mod download -x github.com/benoitkugler/textlayout@v0.0.10
```
This left me with the zip file at `/tmp/foo/go/pkg/mod/cache/download/github.com/benoitkugler/textlayout/@v/v0.0.10.zip`.

Using Linux 7zip, I had no trouble verifying the archive integrity or extracting it. I'll try from windows shortly to see if I can replicate Jon's results.

**Comment by whereswaldon** [comment]
I can't replicate this on Windows:

```powershell
PS C:\Users\chris\Downloads> &'C:\Program Files\7-Zip\7z' x v0.0.10.zip

7-Zip 21.07 (x64) : Copyright (c) 1999-2021 Igor Pavlov : 2021-12-26

Scanning the drive for archives:
1 file, 140517186 bytes (135 MiB)

Extracting archive: v0.0.10.zip
--
Path = v0.0.10.zip
Type = zip
Physical Size = 140517186

Everything is Ok

Files: 2195
Size:       221834174
Compressed: 140517186
```

@jonegil, I'm at a loss. Does this happen if you try to use a different release of `textlayout`? For instance, v0.0.9?

**Comment by jonegil** [comment]
Thank you for examining

I confirm the same error on versions 0.0.9, 0.0.10 and 0.1.0 when downloading both zip and tar.gz from textlayout/tags, and borg when unzip'ing with 7zip and winrar.

**Comment by whereswaldon** [comment]
@jonegil Can you try the steps I followed? The important reason that I used `go mod download` is that it pulls the source code archive that is actually being served when you issue `go get` and similar commands. The one attached to a github tag may not actually be identical.

**Comment by jonegil** [comment]
Today, on a windows computer where v0.0.10 failed to download before, github.com/benoitkugler/textlayout v0.1.0 works well.

**Comment by benoitkugler** [comment]
Great to here !
Thanks @whereswaldon for the debugging.
I think we will dig deeper if someone encounters the same issue.

**Comment by jonegil** [comment]
Not repoening the issue, but noting a surprising effect.


Today, just now, I downloaded https://github.com/benoitkugler/textlayout/archive/refs/tags/v0.1.0.zip on 3 different computers:

Windows PC #1:    54,048,829 bytes
Windows PC #2:  133,201,090 bytes
Mac                     133,021,090 bytes

The former installation fails, while the 2 latter works.
